DB34/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('apotek/', include('apotek.urls')),
    path('produkapotek/', include('produkapotek.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('balai-pengobatan/', include('balaipengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/',include('transaksipembelian.urls')),
    path('pengantaranfarmasi/',include('pengantaranfarmasi.urls')),
    path('listprodukdibeli/',include('listprodukdibeli.urls')),
]

profilpengguna/urls.py
from django.urls import path
from . import views

app_name = "profilpengguna"

urlpatterns = [
    path('', views.profil_view, name='profil'),
    path('profile-adminapotek/', views.admin_apotek_view, name='profiladminapotek'),
    path('profile-konsumen/', views.konsumen_view, name='profilkonsumen'),
    path('profile-kurir/', views.kurir_view, name='profilkurir'),
    path('profile-cs/', views.cs_view, name='profilcs'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.user_login, name='mylogin'),
    path('register/adminapotek/', views.register_view, name='myregister'),
    path('register/konsumen/', views.konsumen_form_view, name='mykonsumenform'),
    path('register/kurir/', views.kurir_form_view, name='mykurirform'),
    path('register/cs/', views.cs_form_view, name='mycsform'),
    path('', views.home, name='home'),
    path('profile-kurir/', views.kurir_view, name='profilkurir'),
    path('logout/', views.user_logout, name='logout'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.db import connection
from django.core.paginator import Paginator
# from django.core.validator import RegexValidator

#----------------LOGIN----------------#
class LoginForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

#----------------REGISTER ADMIN----------------#
class RegAdminForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    nama_lengkap = forms.CharField(label='Nama Lengkap', widget=forms.TextInput(attrs={'class':'form-control'}))
    no_telepon = forms.CharField(label='No Telepon', widget=forms.TextInput(attrs={'class':'form-control'}))

class RegKonsumenForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    nama_lengkap = forms.CharField(label='Nama Lengkap', widget=forms.TextInput(attrs={'class':'form-control'}))
    no_telepon = forms.CharField(label='No Telepon', widget=forms.TextInput(attrs={'class':'form-control'}))
    jenis_kelamin = forms.CharField(label='Jenis Kelamin', widget=forms.TextInput(attrs={'class':'form-control'}))
    tgl_lahir = forms.DateField(
        label='Tanggal Lahir', 
        widget=forms.DateInput(
            attrs={'class':'form-control', 'type':'date'}
            )
        )
    status_alamat1 = forms.CharField(label='Status Alamat', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Status alamat 1' }))
    alamat1 = forms.CharField(label='Alamat', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Alamat 1'}))
    status_alamat2 = forms.CharField(label='Status Alamat', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Status alamat 2' }))
    alamat2 = forms.CharField(label='Alamat', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Alamat 2'}))
    status_alamat3 = forms.CharField(label='Status Alamat', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Status alamat 3' }))
    alamat3 = forms.CharField(label='Alamat', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Alamat 3'}))

class RegCsForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    nama_lengkap = forms.CharField(label='Nama Lengkap', widget=forms.TextInput(attrs={'class':'form-control'}))
    no_telepon = forms.CharField(label='No Telepon', widget=forms.TextInput(attrs={'class':'form-control'}))
    no_ktp = forms.CharField(label='No KTP', widget=forms.TextInput(attrs={'class':'form-control'}))
    no_sia = forms.CharField(label='No SIAK', widget=forms.TextInput(attrs={'class':'form-control'}))

class RegKurirForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    nama_lengkap = forms.CharField(label='Nama Lengkap', widget=forms.TextInput(attrs={'class':'form-control'}))
    no_telepon = forms.CharField(label='No Telepon', widget=forms.TextInput(attrs={'class':'form-control'}))
    nama_perusahaan = forms.CharField(label='Nama perusahaan', widget=forms.TextInput(attrs={'class':'form-control'}))

    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from .forms import LoginForm
from .forms import RegAdminForm, RegCsForm, RegKurirForm, RegKonsumenForm
from django.db import connection
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.
def fetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
# def login_view(request):
#     return render(request, 'login.html')

# def register_view(request):
#     return render(request, 'register.html')

def home(request):
    if request.session.is_empty():
        return render(request, 'homepage:myhomepage')
    else:
        return render(request, 'homepage:landingpage')

# def register_view(request):
#     return render(request, 'register.html')

#def konsumen_form_view(request):
#    return render(request, 'konsumen_form.html')

# def kurir_form_view(request):
#     return render(request, 'kurir_form.html')

# def cs_form_view(request):
#     return render(request, 'cs_form.html')

#----------------LOGIN----------------#
def user_login(request):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                emails = form.cleaned_data["email"]
                password = form.cleaned_data["password"]

                cursor.execute("SET SEARCH_PATH TO FARMAKAMI;")
                cursor.execute("SELECT * FROM PENGGUNA WHERE " + "email = %s AND password = %s;", [emails, password])
             
                user = fetchall(cursor)
                
                if len(user) != 0:
                    user = user[0]
                    email = user["email"]
                    request.session["email"] = email
                    request.session["nama_lengkap"] = user["nama_lengkap"]

                    if check_role(email, "KONSUMEN"):
                        request.session["role"] = "KONSUMEN"
                    elif check_role(email, "ADMIN_APOTEK"):
                        request.session["role"] = "ADMIN_APOTEK"
                    elif check_role(email, "KURIR"):
                        request.session["role"] = "KURIR"
                    elif check_role(email, "CS"):
                        request.session["role"] = "CS"

                    roleNow = request.session["role"]
                    print(roleNow)
                    if roleNow == "ADMIN_APOTEK":
                        return redirect('profilpengguna:profiladminapotek')
                    elif roleNow == "CS":
                        return redirect('profilpengguna:profilcs')
                    elif roleNow == "KURIR":
                        return redirect('profilpengguna:profilkurir')
                    elif roleNow == "KONSUMEN":
                        return redirect('profilpengguna:profilkonsumen')

                messages.error(request, 'Your email and/or password do not match')
                return redirect('users:mylogin')
           
        else:
            
            form = LoginForm()
            return render(request, "login.html", {'form':form})

def check_role(email, role):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO FARMAKAMI;")
        query = "SELECT * FROM " + role + " WHERE email = %s;"
        cursor.execute(query, [email])
        row = fetchall(cursor)

        if len(row) != 0:
            return True
        else:
            return False

#--------LOGOUT----------#
# def userLogout(request):
#     # request.session.flush()
#     return redirect('homepage:homepage')
#----------------REGISTER ADMIN----------------#
def register_view(request):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            form = RegAdminForm(request.POST)
            if form.is_valid():
                email = request.POST.get('email')
                print(email)
                password = request.POST.get('password')
                nama_lengkap = request.POST.get('nama_lengkap')
                no_telepon = request.POST.get('no_telepon')

                id_apotek = 'apd01'
                #Insert into PENGGUNA 
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO PENGGUNA(email, password, nama_lengkap, telepon)"
                                "VALUES ('{}', '{}', '{}', '{}');".format(email,password,nama_lengkap,no_telepon))

                #Insert into APOTEKER
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO APOTEKER(email) VALUES ('{}');".format(email))

                #Insert into ADMIN_APOTEK
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO ADMIN_APOTEK (email,id_apotek) VALUES('{}', '{}');".format(email,id_apotek))

                request.session['email'] = email
                request.session["role"] = "ADMIN_APOTEK"
                return redirect('profilpengguna:profiladminapotek')
    form = RegAdminForm()
    args = {
        'form' : form,
    }
    return render(request, 'register.html', args)

#----------------REGISTER KONSUMEN----------------#
def konsumen_form_view(request):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            form = RegKonsumenForm(request.POST)
            if form.is_valid():
                email = request.POST.get('email')
                password = request.POST.get('password')
                nama_lengkap = request.POST.get('nama_lengkap')
                no_telepon = request.POST.get('no_telepon')
                jenis_kelamin = request.POST.get('jenis_kelamin')
                tgl_lahir = request.POST.get('tgl_lahir')
                status_alamat1 = request.POST.get('status_alamat1')
                alamat1  = request.POST.get('alamat1')
                status_alamat2 = request.POST.get('status_alamat2')
                alamat2  = request.POST.get('alamat2')
                status_alamat3 = request.POST.get('status_alamat3')
                alamat3  = request.POST.get('alamat3')
                dictalamat = {
                    "alamatkey1" : ["alamat1", "status_alamat1"],
                    "alamatkey2" : ["alamat2", "status_alamat2"],
                    "alamatkey3" : ["alamat3", "status_alamat3"],
                }
                id_konsumen = get_id_konsumen()

                #Insert into PENGGUNA 
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO PENGGUNA(email, password, nama_lengkap, telepon)"
                                "VALUES ('{}', '{}', '{}', '{}');".format(email,password,nama_lengkap,no_telepon))

                #Insert into KONSUMEN
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO KONSUMEN(id_konsumen, email, jenis_kelamin, tanggal_lahir)"
                                "VALUES ('{}', '{}', '{}', '{}');".format(id_konsumen, email, jenis_kelamin, tgl_lahir))

                #Insert into ALAMAT
                for da in dictalamat :
                    da['alamatkey1'] = da['alamatkey1'].split(',')
                    da['alamatkey2'] = st['alamatkey2'].split(',')
                    da['alamatkey3'] = st['alamatkey3'].split(',')
                    
                    qinsert =  """
                    INSERT INTO ALAMAT_KONSUMEN (id_konsumen, alamat, status)
                    VALUES ('%s', '%s', '%s');
                    """ %(id_konsumen, da[0], da[1])
                    cursor.execute(qinsert)

                request.session['email'] = email
                request.session["role"] = "KONSUMEN"
                return redirect('profilpengguna:profilkonsumen')
    form = RegKonsumenForm()
    args = {
        'form' : form,
    }
    return render(request, 'konsumen_form.html', args)

def get_id_konsumen():
    query = """
    SELECT CONCAT('kd0', CAST (last as integer)+1)
    FROM ( SELECT SUBSTRING(id_konsumen FROM 3 ) as last FROM KONSUMEN
    ORDER BY id_konsumen DESC LIMIT 1) A;
    """
    cursor = connection.cursor()
    cursor.execute("SET search_path TO FARMAKAMI;")
    cursor.execute(query)
    id_konsumen_baru = str(cursor.fetchone()[0])

    return id_konsumen_baru

#---------- REGIS CS -----------#
def cs_form_view(request):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            form = RegCsForm(request.POST)
            if form.is_valid():
                email = request.POST.get('email')
                password = request.POST.get('password')
                nama_lengkap = request.POST.get('nama_lengkap')
                no_telepon = request.POST.get('no_telepon')
                no_ktp = request.POST.get('no_ktp')
                no_sia = request.POST.get('no_sia')
               
                #Insert into PENGGUNA 
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO PENGGUNA(email, password, nama_lengkap, telepon)"
                                "VALUES ('{}', '{}', '{}', '{}');".format(email,password,nama_lengkap,no_telepon))

                #Insert into APOTEKER
                cursor.execute("SET search_path TO farmakami;")
                cursor.execute("INSERT INTO APOTEKER(email) VALUES ('{}');".format(email))

                #Insert into CS
                cursor.execute("SET search_path TO farmakami;")

users/templates/cs_form.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:myregister' %}">Admin Apotek</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:mykonsumenform' %}">Konsumen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:mykurirform' %}">Kurir</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:mycsform' %}">CS</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Register as Customer Service</center></h4></p>
      <form action="{% url 'users:mycsform' %}" method="POST">
        {% csrf_token %}
        <div class="form-group .justify-content-start ">
          <label for="exampleInputEmail1">Email address</label>
          {{ form.email }}
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          {{ form.password }}
        </div>

        <div class="form-group">
          <label for="validationDefault01">Nama lengkap</label>
          {{ form.nama_lengkap }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">No Telepon</label>
          {{ form.no_telepon }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">No KTP</label>
          {{ form.no_ktp }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">Nomor SIA</label>
          {{ form.no_sia }}
        </div>

        <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
      </form>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/konsumen_form.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:myregister' %}">Admin Apotek</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'users:mykonsumenform' %}">Konsumen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:mykurirform' %}">Kurir</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'users:mycsform' %}">CS</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Register as Konsumen</center></h4></p>
      <form action="{% url 'users:mykonsumenform' %}" method="POST">
        {% csrf_token %}
        <div class="form-group .justify-content-start ">
          <label for="exampleInputEmail1">Email address</label>
          {{ form.email }}
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          {{ form.password }}
        </div>

        <div class="form-group">
          <label for="validationDefault01">Nama lengkap</label>
          {{ form.nama_lengkap }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">No Telepon</label>
          {{ form.no_telepon }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">Jenis Kelamin</label>
          {{ form.jenis_kelamin }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">Tanggal Lahir</label>
          {{ form.tgl_lahir }}
        </div>
        
        <div class="form-group">
          <label for="validationDefault02">Alamat</label>
          <button type="button" class="btn bg-warning " onclick="addAlamat()">+</button>
          <div class="form-group" id="daftar-alamat">
            {{ form.status_alamat1 }}
            {{ form.alamat1 }}
            {{ form.status_alamat2 }}
            {{ form.alamat2 }}
            {{ form.status_alamat3 }}
            {{ form.alamat3 }}
          </div>
        </div>

        <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
      </form>
      </div>
    </div>
  </div>
  <script>
    function addAlamat(e){
      const div = document.createElement('input');
      div.className = "form-control inputAlamat";
      div.innerHTML = `
      <input id="validationDefault02" type="text" class="form-control" placeholder="Alamat">
      `;
      document.getElementById("daftar-alamat").appendChild(div);
      }
  </script>


{% endblock %}

users/templates/kurir_form.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:myregister' %}">Admin Apotek</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:mykonsumenform' %}">Konsumen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active " href="{% url 'users:mykurirform' %}">Kurir</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'users:mycsform' %}">CS</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4  ">
        <p class="tulisan_login"><h4><center>Register as Kurir</center></h4></p>
      <form action="{% url 'users:mykurirform' %}" method="POST">
          {% csrf_token %}
          <div class="form-group .justify-content-start ">
            <label for="exampleInputEmail1">Email address</label>
            {{ form.email }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            {{ form.password }}
          </div>

          <div class="form-group">
            <label for="validationDefault01">Nama lengkap</label>
            {{ form.nama_lengkap }}
          </div>

          <div class="form-group">
            <label for="validationDefault02">No Telepon</label>
            {{ form.no_telepon }}
          </div>

          <div class="form-group">
            <label for="validationDefault02">Nama Perusahaan</label>
            {{ form.nama_perusahaan }}
          </div>
          
          <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
      </form>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/login.html
{% extends "base.html" %}


{% block style_content %}
<style>
    body{
        background-color: #dc3545;
    }

    .divlogin{
        margin-top: 80px;
    }
</style>
{% endblock %}

{% block page_content %}


<div class="outer-form divlogin container form-column col-md-4 ">
    <p class="tulisan_login"><h2><center>LOGIN</center></h4></p>
  <form action="{% url 'users:mylogin' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      {{ form.email }}
     
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      {{ form.password }}
    </div>
    {% if messages %}
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }} text-danger"{% endif %}>{{ message }}</p>
    {% endfor %}
    {% endif %}
    <!-- <button type="submit" class="btn btn-primary  btn-am">Login</button> -->
    <!-- <a href="{% url 'profilpengguna:profil' %}" ><button type="submit" class="btn btn-primary btn-am">Login</button></a> -->
    <input class="btn btn-primary" type="submit" value="Log in">
    
    
  </form>
</div>
{% endblock %}

users/templates/profil-pengguna-kurir.html
{% extends "base.html" %}

{% block page_content %}

<body>
    <div style="margin-top: 40px;"  class=" outer-form container">
        <h2><center>Selamat datang, {{ data_profil.nama_lengkap }} sebagai Kurir</center></h2>
        <div style="margin-top: 15px; " class="container">
            <p>Nama Lengkap: {{ data_profil.nama_lengkap }}</p>
            <p>No Telepon: {{ data_profil.telepon }} </p>
            <p>Email: {{ data_profil.email }}</p>
            <p>Nama perusahan: {{ data_profil.nama_perusahaan }}</p>
        </div>
    </div>
</body>
{% endblock %}

users/templates/register.html
{% extends "base.html" %}



{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'users:myregister' %}">Admin Apotek</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:mykonsumenform' %}">Konsumen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:mykurirform' %}">Kurir</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'users:mycsform' %}">CS</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Register as Admin Apotek</center></h4></p>
      <form action="{% url 'users:myregister' %}" method="POST">
        {% csrf_token %}
        <div class="form-group .justify-content-start ">
          <label for="exampleInputEmail1">Email address</label>
          {{ form.email }}
         
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          {{ form.password }}
        </div>

        <div class="form-group">
          <label for="validationDefault01">Nama lengkap</label>
          {{ form.nama_lengkap }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">No Telepon</label>
          {{ form.no_telepon }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
        <!-- <button type="submit" class="btn btn-primary  btn-am">Sign Up</button> -->
      </form>
      </div>
    </div>
  </div>

{% endblock %}