DB34/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('apotek/', include('apotek.urls')),
    path('produkapotek/', include('produkapotek.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('balai-pengobatan/', include('balaipengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/',include('transaksipembelian.urls')),
    path('pengantaranfarmasi/',include('pengantaranfarmasi.urls')),
    path('listprodukdibeli/',include('listprodukdibeli.urls')),
]

transaksipembelian/urls.py
from django.urls import path
from . import views

app_name = "transaksipembelian"

urlpatterns = [
    path('create-transaksipembelian/',views.create_transaksipembelian, name='create-transaksipembelian'),
    path('daftar-transaksipembelian/',views.daftar_transaksipembelian,name='daftar-transaksipembelian'),
    path('update-transaksipembelian/<id>',views.update_transaksipembelian,name='update-transaksipembelian'),
    path('delete-transaksipembelian/<id>',views.delete_transaksipembelian,name='deletransaksi<id>'),
    
]

transaksipembelian/models.py
from django.db import models

# Create your models here.

transaksipembelian/forms.py
from django import forms
from django.db import connection

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
def idKonsumen():
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to FARMAKAMI;"
                        "SELECT DISTINCT id_konsumen "
                        "FROM KONSUMEN;" )
        id_k = dictfetchall(cursor)
        daftar_id_k = []
        for id in id_k:
            temp = []
            temp.append(id['id_konsumen'])
            temp.append(id['id_konsumen'])
            daftar_id_k.append(tuple(temp))
        return daftar_id_k
pillihan_id_konsumen = idKonsumen()

# def id_konsumen_terntentu(email):
#      with connection.cursor() as cursor:
#         cursor.execute("SET search_path to FARMAKAMI;"
#                         "SELECT  id_konsumen "
#                         "FROM KONSUMEN "
#                         "WHERE email = '{}';".format(email) )
#         id_k = dictfetchall(cursor)
#         daftar_id_k = []
#         for id in id_k:
#             temp = []
#             temp.append(id['id_konsumen'])
#             temp.append(id['id_konsumen'])
#             daftar_id_k.append(tuple(temp))
#         return daftar_id_k
class createTransaksiPembelianForm(forms.Form):
    # roleNow = request.session.get("role")
    # if roleNow == "KONSUMEN":
    #     email = request.session.get("email")
    #     id_konsumen = forms.CharField(label = 'ID Konsumen', widget=forms.HiddenInput(), initial=)
    id_konsumen = forms.CharField(label = 'ID Konsumen',widget=forms.Select(choices=pillihan_id_konsumen, attrs={'class': 'form-control'}))
class updateTransaksiPembelianForm(forms.Form):
    id_konsumen =  forms.CharField(label = 'ID Konsumen',widget=forms.Select(choices=pillihan_id_konsumen, attrs={'class': 'form-control'}))

transaksipembelian/views.py
from django.shortcuts import render, redirect
from django.db import connection
from .forms import createTransaksiPembelianForm
import datetime
from django.core.paginator import Paginator
from .forms import updateTransaksiPembelianForm

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def create_transaksipembelian(request):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            id_konsumen = request.POST.get('id_konsumen')
            cursor.execute("SET search_path TO FARMAKAMI;")
            cursor.execute("SELECT COUNT(*) AS jumlah_transaksi FROM TRANSAKSI_PEMBELIAN;")
            id_transaksi = 'trd' +  str(int((dictfetchall(cursor)[0])['jumlah_transaksi']) + 1)
            waktu = datetime.datetime.now()
            total_pembayaran = 0

            #INSERT into TRANSAKSI PEMBELIAN
            cursor.execute("SET search_path to FARMAKAMI;")
            cursor.execute("INSERT INTO TRANSAKSI_PEMBELIAN(id_konsumen, id_transaksi_pembelian, waktu_pembelian, total_pembayaran) "
                            "VALUES ('{}', '{}', '{}', '{}');".format(id_konsumen,id_transaksi,waktu,total_pembayaran))
            return redirect("transaksipembelian:daftar-transaksipembelian")
    form = createTransaksiPembelianForm()
    args ={
        'form' : form
    }
    return render(request, 'create-transaksipembelian.html',args)
def daftar_transaksipembelian(request):
    roleNow = request.session.get("role")
    email = request.session.get("email")
    if roleNow == "KONSUMEN":
        query = """
        SELECT T.id_transaksi_pembelian, T.waktu_pembelian, T.total_pembayaran, T.id_konsumen
        FROM TRANSAKSI_PEMBELIAN T, KONSUMEN K
        WHERE T.id_konsumen = K.id_konsumen AND K.email = '%s';
        """%(email)
    else:
        query = """
        SELECT * 
        FROM TRANSAKSI_PEMBELIAN;
        """
    cursor = connection.cursor()
    cursor.execute("SET search_path to FARMAKAMI;")
    cursor.execute(query)

    data_transaksipembelian = fetch(cursor)
    form = updateTransaksiPembelianForm()
    args = {
        'form': form,
        'data_transaksipembelian': data_transaksipembelian
    }
    return render(request,'daftar-transaksipembelian.html', args)
def update_transaksipembelian(request,id):
    id_konsumen = request.POST.get('u-id-konsumen')
    query = """
    UPDATE TRANSAKSI_PEMBELIAN
    SET id_konsumen = '%s' WHERE id_transaksi_pembelian = '%s';
    """ %(id_konsumen,id)
    cursor = connection.cursor()
    cursor.execute("SET search_path to FARMAKAMI;")
    cursor.execute(query)

    return redirect('transaksipembelian:daftar-transaksipembelian')

def delete_transaksipembelian(request,id):
    query="""
    DELETE FROM TRANSAKSI_PEMBELIAN
    WHERE id_transaksi_pembelian = '%s';
    """ %(id)

    cursor = connection.cursor()
    cursor.execute("SET search_path to FARMAKAMI;")
    cursor.execute(query)

    return redirect('transaksipembelian:daftar-transaksipembelian')
def fetch(cursor):
    columns = [col[0] for col in cursor.description]
    return[dict(zip(columns, row)) for row in cursor.fetchall()]

transaksipembelian/templates/create-transaksipembelian.html
{% extends "base.html" %}

{% block page_content %}
<body>
    <div class=" outer-form d-flex align-items-center flex-column">
        <h2><center>FORM PEMBUATAN TRANSAKSI PEMBELIAN</center></h2>
        <form action="{% url 'transaksipembelian:create-transaksipembelian' %}" class=" text-center" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input action="POST" type="submit" value= "Create" class="btn btn-success mt-3">
        </form>
    </div>
</body>
{% endblock %}

transaksipembelian/templates/daftar-transaksipembelian.html
{% extends "base.html" %}

{% block page_content %}
<div class="container">
    <h2><center>DAFTAR TRANSAKSI PEMBELIAN</center></h2>
</div>
{% if request.session.role == "ADMIN_APOTEK" %}
<center>
<a href="/transaksipembelian/create-transaksipembelian/">
    <button type="button" class="btn btn-success ">Buat Transaksi Pembelian</button>
</a>
</center>
{% endif %}
<div class="mt-2 mx-5 my-5">
    <table class="table table-hover">
        <thead class="bg-danger text-white align-items-center;">
            <tr>
                <th>ID Transaksi</th>
                <th>Waktu Pembelian</th>
                <th>Total Pembayaran</th>
                <th>ID Konsumen</th>
                {% if request.session.role == "ADMIN_APOTEK" %}
                <th>Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>

            {% for transaksipembelian in data_transaksipembelian %}
            <tr>
                <td>{{ transaksipembelian.id_transaksi_pembelian }}</td>
                <td>{{ transaksipembelian.waktu_pembelian }}</td>
                <td>{{ transaksipembelian.total_pembayaran }}</td>
                <td>{{ transaksipembelian.id_konsumen }}</td>
                {% if request.session.role == "ADMIN_APOTEK" %}
                <td>
                    

                    <button class = "btn btn-primary btn-am bg-success update" 
                    id-transaksi = "{{ transaksipembelian.id_transaksi_pembelian }}"
                    waktu-pembelian = "{{ transaksipembelian.waktu_pembelian }}"
                    total-pembayaran = "{{ transaksipembelian.total_pembayaran }}"
                    id-konsumen = "{{ transaksipembelian.id_konsumen }}"
                    > Update </button>
                    <div class="modal fade" id="update-transaksipembelian" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLongTitle">Form Update Transaksi Pembelian</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" action="/" id="form-update">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="disabledTextInput">ID Transaksi</label>
                                        <input type="text" class="form-control " id="id-transaksi" name="u-id-transaksi" disabled>
                                    </div>
                                    <div class="form-group">
                                        <label for="disabledTextInput">Waktu Pembelian</label>
                                        <input type="text" class="form-control " id="waktu-transaksi" name="u-waktu-transaksi"  disabled>
                                    </div>
                                    <div class="form-group">
                                        <label for="disabledTextInput">Total Pembayaran</label>
                                        <input type="text" class="form-control " id="total-pembayaran" name="u-total-pembayaran"  disabled>
                                    </div>
                                   
                                    <div class="form-group">
                                        <label for="validationDefault01">ID Konsumen</label>
                                        <select class="form-control" id="id-konsumen" name="u-id-konsumen"  required>
                                          <option> kd01 </option>
                                          <option> kd02 </option>
                                          <option> kd03 </option>
                                          <option> kd04 </option>
                                          <option> kd05 </option>
                                        </select>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        
                                        <button type="submit" class="btn bg-success btn-primary ">Submit</button>
                                        
                                    </div>
                                </form>
                            </div>
                        </div>
                      </div>
                    </div>
                </div>  
                 <a href="/transaksipembelian/delete-transaksipembelian/{{ transaksipembelian.id_transaksi_pembelian }}">
                    <button type="button" class="btn btn-primary btn-am bg-danger">Delete</button>
                </a> 
                </td>
                {% endif %}
            </tr>

            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block script_content %}

  
<script>
  $('.update').click(function(){
    $('#update-transaksipembelian').modal();
  var idtransaksipembelian = $(this).attr('id-transaksi')
  var waktu = $(this).attr('waktu-pembelian')
  var total = $(this).attr('total-pembayaran')

  
  $('#form-update').attr('action', '/transaksipembelian/update-transaksipembelian/'+idtransaksipembelian)
  $('#id-transaksi').val(idtransaksipembelian)
  $('#waktu-transaksi').val(waktu)
  $('#total-pembayaran').val(total)

  })

</script>
{% endblock %}

transaksipembelian/templates/update-transaksipembelian.html
{% extends "base.html" %}

{% block page_content %}
<div class=" outer-form container">
    <h2><center>FORM UPDATE TRANSAKSI PEMBELIAN</center></h2>

<form action="" class=" align-items-center">
    <div class="form-group row">    
        <label for="id transaksis" class="col-sm-4 col-form-label">ID Transaksi</label>
        <div class="col-sm-4">
        <input value ="1" disabled>
        </div>
    </div>
    <div class="form-group row">
        <label for="waktupemmbelian" class="col-sm-4 col-form-label">Waktu Pembelian</label>
        <div class="col-sm-4">
        <input value="17 April 2020 17:20:20" disabled>
        </div>
    </div>
    <div class="form-group row">
        <label for="totalpembayaran" class="col-sm-4 col-form-label">Total Pembayaran</label>
        <div class="col-sm-4">
        <input value ="10000" disabled>
        </div>
    </div>
    <div class="form-group row">
        <label for="idkonsumen" class="col-sm-4 col-form-label">ID Konsumen</label>
            <div class="col-sm-4">
                <select id="idkonsumen" class="form-control">
                    <option selected>Pilih</option>
                    <option>9</option>
                    <option>kd01</option>
                    <option>kd02</option>
                    <option>...</option>
                </select>
            </div>
    </div>
    <div class="col-md text-center">
        <input action="POST" type="submit" value= "Update" class="btn btn-success">
    </div>
</form>
</div>
{% endblock %}