DB34/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('apotek/', include('apotek.urls')),
    path('produkapotek/', include('produkapotek.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('balai-pengobatan/', include('balaipengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/',include('transaksipembelian.urls')),
    path('pengantaranfarmasi/',include('pengantaranfarmasi.urls')),
    path('listprodukdibeli/',include('listprodukdibeli.urls')),
]

pengantaranfarmasi/urls.py
from django.urls import path
from . import views

app_name = "pengantaranfarmasi"

urlpatterns = [
    path('create-pengantaranfarmasi/', views.create_pf_view, name='create-pf'),
    path('daftar-pengantaranfarmasi/',views.daftar_pf_view,name='daftar-pf'),
    path('update-pengantaranfarmasi/',views.update_pf_view,name='update-pf'),
  
]

pengantaranfarmasi/models.py
from django.db import models

# Create your models here.

pengantaranfarmasi/views.py
from django.shortcuts import render

# Create your views here.
def create_pf_view(request):
    return render(request, 'create-pf.html')
def daftar_pf_view(request):
    return render(request,'daftar-pf.html')
def update_pf_view(request):
    return render(request,'update-pf.html')

pengantaranfarmasi/templates/create-pf.html
{% extends "base.html" %}

{% block page_content %}

<h1><center>Buat List Pengantaran Farmasi</center></h2>
    <div class="outer-form form-column col-4 ">
      <p class="tulisan_login"><h4><center>Form Buat List Produk Dibeli</center></h4></p>
   
      <form >
        <div class="form-group">
          <label for="validationDefault05">ID Produk</label>
          <div class="form-group" id="idproduk">
            <select class="form-control dropdown-id">
                <option>Pilih...</option>
                <option>...</option>
            </select>
          </div>
        </div>
        <div class="form-group">
          <label for="validationDefault01">Waktu</label>
          <input type="date" id="day" name="day">
        </div>
        <div class="form-group">
            <label for="validationDefault01">Biaya Kirim</label>
            <input type="text" class="form-control " id="validationDefault01" placeholder="Biaya Kirim">
          </div>
  
        <button type="submit" class="btn btn-primary  btn-am">Submit</button>
       
    </form>
  </div>

{% endblock %}

pengantaranfarmasi/templates/daftar-pf.html
{% extends "base.html" %}

{% block page_content %}

<h2><center>Daftar Pengantaran Farmasi</center></h2>
<div class="tabelmargin table-responsive">
    <table class="table justify-content-center">
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">ID Pengantaran</th>
                <th scope="col">ID Kurir</th>
                <th scope="col">ID Transaksi</th>
                <th scope="col">Waktu</th>
                <th scope="col">Status</th>
                <th scope="col">Biaya Kirim</th>
                <th scope="col">Total Biaya</th>
                <th scope="col">Action [ADMIN]</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1d</th>
                <td>1b</td>
                <td>12b</td>
                <td>17 April 2020 17:20:20 </td>
                <td>Done</td>
                <td>10000</td>
                <td>20000</td>
                <td>
                    <!-- <a href="{% url 'produkapotek:update-produkapotek' %}" class="btn btn-success" role="button">Update </a> -->
                    <a href="{% url 'pengantaranfarmasi:update-pf' %}" class="btn btn-info" role="button">Update</a>
                    <!-- <a href="#" class="btn btn-danger" role="button">Delete</a> -->
                    <button type="button" class="btn btn-primary btn-am bg-danger">Delete</button>
                </td>
            </tr>
            <tr>
                <th scope="row">1das</th>
                <td>1asa</td>
                <td>12baa</td>
                <td>17 April 2020 17:20:20 </td>
                <td>Done</td>
                <td>15500</td>
                <td>20000</td>
                <td>
                    <!-- <a href="{% url 'produkapotek:update-produkapotek' %}" class="btn btn-success" role="button">Update </a> -->
                    <a href="{% url 'pengantaranfarmasi:update-pf' %}" class="btn btn-info" role="button">Update</a>
                    <!-- <a href="#" class="btn btn-danger" role="button">Delete</a> -->
                    <button type="button" class="btn btn-primary btn-am bg-danger">Delete</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

pengantaranfarmasi/templates/update-pf.html
{% extends "base.html" %}

{% block page_content %}

<div class=" outer-form container">
    <h2><center>FORM UPDATE Pengantaran Farmasi</center></h2>

<form action="" class=" align-items-center">
    <div class="form-group row">
        <label for="idkonsumen" class="col-sm-4 col-form-label">ID Pengantaran</label>
        <div class="col-sm-4">
        <input value ="1" disabled>
        </div>
    </div>
    <div class="form-group row">
        <label for="idkonsumen" class="col-sm-4 col-form-label">ID Kurir</label>
            <div class="col-sm-4">
                <select id="idkonsumen" class="form-control">
                    <option selected>Pilih</option>
                    <option>9</option>
                    <option>kd01</option>
                    <option>kd02</option>
                    <option>...</option>
                </select>
            </div>
    </div>
    <div class="form-group row">
        <label for="idkonsumen" class="col-sm-4 col-form-label">ID Transaksi</label>
            <div class="col-sm-4">
                <select id="idkonsumen" class="form-control">
                    <option selected>Pilih</option>
                    <option>9</option>
                    <option>kd01</option>
                    <option>kd02</option>
                    <option>...</option>
                </select>
            </div>
    </div>
    <div class="form-group row">
        <label for="waktupemmbelian" class="col-sm-4 col-form-label">Waktu</label>
        <div class="col-sm-4">
        <input value="17 April 2020 17:20:20" disabled>
        </div>
    </div>
    <div class="form-group row">
        <label for="totalpembayaran" class="col-sm-4 col-form-label">Biaya Kirim</label>
        <div class="col-sm-4">
        <input value ="10000" disabled>
        </div>
    </div>
    <div class="form-group row">
        <label for="totalpembayaran" class="col-sm-4 col-form-label">Total Biaya</label>
        <div class="col-sm-4">
        <input value ="200000" disabled>
        </div>
    </div>
    <div class="col-md text-center">
        <input action="POST" type="submit" value= "Update" class="btn btn-success">
    </div>
</form>
</div>

{% endblock %}