DB34/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('apotek/', include('apotek.urls')),
    path('produkapotek/', include('produkapotek.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('balai-pengobatan/', include('balaipengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/',include('transaksipembelian.urls')),
    path('pengantaranfarmasi/',include('pengantaranfarmasi.urls')),
    path('listprodukdibeli/',include('listprodukdibeli.urls')),
]

apotek/urls.py
from django.urls import path
from . import views

app_name = "apotek"

urlpatterns = [
    path('createapotek/', views.create_apotek, name='mycreateapotek'),
    path('formcreateapotek/', views.form_create_apotek, name='myformcreateapotek'),
    path('updateapotek/<id>', views.update_apotek, name='myupdateapotek'),
    path('listapotek/', views.list_apotek, name='mylistapotek'),
    path('deleteapotek/<id>', views.delete_apotek, name='mydeleteapotek<id>'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.homepage_view, name='myhomepage'),
    path('landingpage/', views.landing_view, name='landingpage'),
]

obat/urls.py
from django.urls import path
from . import views

app_name = "obat"

urlpatterns = [
    path('daftarobat/', views.daftar_obat_view, name='mydaftarobat'),
    path('formbuatobat/', views.form_buat_obat_view, name='myformbuatobat'),
    path('buatobat/', views.buat_obat, name='mybuatobat'),
    path('updateobat/<id>', views.update_obat, name='myupdateobat'),
    path('deleteobat/<id>', views.delete_obat, name='mydeleteobat<id>'),
]

produkapotek/urls.py
from django.urls import path, include
from . import views

app_name = "produkapotek"

urlpatterns = [
    path('createpa/', views.create_pa, name='mycreatepa'),
    path('updatepa/<idpro>/<idapo>', views.update_pa, name='myupdatepa'),
    path('listpa/', views.list_pa, name='mylistpa'),
    path('formcreatepa/', views.form_create_produk_apotek, name='myformcreatepa'),
    path('deletepa/<idpro>/<idapo>', views.delete_pa, name='mydeletepa<idpro>/<idapo>'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.user_login, name='mylogin'),
    path('register/adminapotek/', views.register_view, name='myregister'),
    path('register/konsumen/', views.konsumen_form_view, name='mykonsumenform'),
    path('register/kurir/', views.kurir_form_view, name='mykurirform'),
    path('register/cs/', views.cs_form_view, name='mycsform'),
    path('', views.home, name='home'),
    path('profile-kurir/', views.kurir_view, name='profilkurir'),
    path('logout/', views.user_logout, name='logout'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.db import connection
from django.core.paginator import Paginator
from django.http import HttpResponse

# Create your views here.
def homepage_view(request):
    return render(request, 'homepage.html')

def landing_view(request):
    return render(request, 'landingpage.html')

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'farmakamiiconnew.png' %}">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title> Farma Kami 34</title>
        {% block style_content %}

        {% endblock %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-white text-danger">
                <a class="navbar-brand" href="{% url 'homepage:myhomepage' %}">
                    <img style="width:150px;height:50px;margin-left: 20px;" src="{% static 'farmakamilogonew.png' %}">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse justify-content-end collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav">
                    
                    
                    <li class="nav-item">
                      <a class="nav-link text-danger" href="{% url 'users:mylogin' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-danger" href="{% url 'users:myregister' %}">Register</a>
                    </li>
                    <!--
                    <li class="nav-item active">
                      <a class="nav-link text-danger" href="{% url 'homepage:myhomepage' %}">Home <span class="sr-only">(current)</span></a>
                    </li>-->
                    <li class="nav-item">
                      <a class="nav-link text-danger" href="{% url 'profilpengguna:profil' %}">Profile</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-danger" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       Balai Pengobatan dan Apotek
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.session.role == "ADMIN_APOTEK" %}
                        <a class="dropdown-item" href="{% url 'balaipengobatan:myformbuatbp' %}">Buat Balai Pengobatan</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'balaipengobatan:mydaftarbp' %}">Daftar Balai Pengobatan</a>
                        {% if request.session.role == "ADMIN_APOTEK" %}
                        <a class="dropdown-item" href="{% url 'apotek:myformcreateapotek' %}">Buat Apotek</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'apotek:mylistapotek' %}">Daftar Apotek</a>
                      </div>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-danger" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       Produk Apotek
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.session.role == "ADMIN_APOTEK" %}
                        <a class="dropdown-item" href="{% url 'produkapotek:myformcreatepa' %}">Buat Produk Apotek</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'produkapotek:mylistpa' %}">Daftar Produk Apotek</a>
                        <a class="dropdown-item" href="{% url 'obat:myformbuatobat' %}">Buat Obat</a>
                        <a class="dropdown-item" href="{% url 'obat:mydaftarobat' %}">Daftar Obat</a>
                        <a class="dropdown-item" href="#">Buat Alat Medis</a>
                        <a class="dropdown-item" href="#">Daftar Alat Medis</a>
                      </div>
                    </li>

                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-danger" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       Daftar Transaksi
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'transaksipembelian:daftar-transaksipembelian' %}">Daftar Transaksi Pembelian</a>
                        <a class="dropdown-item" href="{% url 'listprodukdibeli:create-listpd' %}">Buat List Produk Dibeli</a>
                        <a class="dropdown-item" href="{% url 'listprodukdibeli:daftar-listpd' %}">Daftar List Produk Dibeli</a>
                      </a>
                      </div>
                    </li>

                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-danger" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       Pengantaran Farmasi
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.session.role == "ADMIN_APOTEK" %}
                        <a class="dropdown-item" href="{% url 'pengantaranfarmasi:create-pf' %}">Buat Pengantaran Farmasi</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'pengantaranfarmasi:daftar-pf' %}">Daftar Pengantaran Farmasi</a>
                      </a>
                      </div>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-danger" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                   
                    {% block navbar_content %}

                    {% endblock %}
                    <!-- Untuk dropdown 
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                    </li>
                    -->
                  </ul>
                </div>
              </nav>
        </header>
        {% block page_content %}

        {% endblock %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% block script_content %}

        {% endblock %}
    </body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<!--
<h1> <center> Welcome to Farma Kami 34 </center></h1>
<center><img src="{% static 'farmakamilogo.jpg' %}"></center>
-->

<div class="col-lg-6 col-md-6 col-sm-12 d-flex justify-content-center align-items-left flex-column text-welcome">
  <div class="welcome1">
      <h2 class="mb-3 text1">Welcome to <br>Farma Kami 34</h2>
  </div>
  <div class="welcome2 mb-3 text2 typewriter">
      <p>We serve the best for you and keep you to <span class ="orange"><strong>#StayAtHome </strong></span></p>
  </div>
  <div class="cta-but d-flex flex-row">
    <a href="{% url 'users:mylogin' %}">
      <button class="btn btn-primary mr-2 my-2 my-sm-0 rounded-lg btn-login"  type="submit">Login</button>
    </a>
    <a href="{% url 'users:myregister' %}">
      <button class="btn btn-outline-primary my-2 my-sm-0 rounded-lg btn-register" type="submit">Register</button>     
    </a>
    </div>
</div>
<!--
<div class="card-deck">
<div class="row mx-auto">
    <div class="col-sm-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Login</h5>
          <p class="card-text ">Login here if you have been registered!</p>
          <a href="{% url 'users:mylogin' %}" class="btn btn-primary bg-warning text-white">Sign in</a>
        </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Register</h5>
          <p class="card-text ">Register here if you have not been registered yet!</p>
          <a href="{% url 'users:myregister' %}" class="btn btn-primary bg-danger text-white">Click here to register</a>
        </div>
      </div>
    </div>
  </div>
</div>-->
<div class="col-lg-6 col-md-6 col-sm-12 d-flex align-items-right flex-column">
<img class="kanan img-responsive" src="{% static 'gambarhomepage.jpg' %}">
</div>

{% endblock %}

homepage/templates/landingpage.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<!--
<h1> <center> Welcome to Farma Kami 34 </center></h1>
<center><img src="{% static 'farmakamilogo.jpg' %}"></center>
-->

<div class="col-lg-6 col-md-6 col-sm-12 d-flex justify-content-center align-items-left flex-column text-welcome">
  <div class="welcome1">
      <h2 class="mb-3 text1">Welcome to <br>Farma Kami 34</h2>
  </div>
  <div class="welcome2 mb-3 text2 typewriter">
      <p>We serve the best for you and keep you to <span class ="orange"><strong>#StayAtHome </strong></span></p>
  </div>
  <!-- <div class="cta-but d-flex flex-row">
      <button class="btn btn-primary mr-2 my-2 my-sm-0 rounded-lg btn-login" href="{% url 'users:mylogin' %}" type="submit">Login</button>
      <button class="btn btn-outline-primary my-2 my-sm-0 rounded-lg btn-register" href="{% url 'users:myregister' %}" type="submit">Register</button>     
  </div> -->
</div>
<!--
<div class="card-deck">
<div class="row mx-auto">
    <div class="col-sm-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Login</h5>
          <p class="card-text ">Login here if you have been registered!</p>
          <a href="{% url 'users:mylogin' %}" class="btn btn-primary bg-warning text-white">Sign in</a>
        </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Register</h5>
          <p class="card-text ">Register here if you have not been registered yet!</p>
          <a href="{% url 'users:myregister' %}" class="btn btn-primary bg-danger text-white">Click here to register</a>
        </div>
      </div>
    </div>
  </div>
</div>-->
<div class="col-lg-6 col-md-6 col-sm-12 d-flex align-items-right flex-column">
<img class="kanan img-responsive" src="{% static 'gambarhomepage.jpg' %}">
</div>

{% endblock %}